from typing import Protocol, ContextManager
from app.models.domain import Progress

class Repository(Protocol):
    """Implement all methods; transaction must serialize a student's read/write unit."""
    persistent: bool
    def transaction(self, student_id: int | None = None) -> ContextManager: ...
    def get_topics(self) -> list[dict]: ...
    def get_topic(self, topic_id: int) -> dict | None: ...
    def get_questions(self, topic_id: int) -> list[dict]: ...
    def get_diagnostic_questions(self) -> list[dict]: ...
    def create_student(self, name: str) -> dict: ...
    def get_student(self, student_id: int) -> dict | None: ...
    def mark_diagnostic_completed(self, student_id: int) -> None: ...
    def get_progress(self, student_id: int) -> list[Progress]: ...
    def update_progress(self, student_id: int, progress: Progress) -> None: ...
    def add_attempt(self, student_id: int, attempt: dict) -> dict: ...
    def get_attempts_for_student(self, student_id: int) -> list[dict]: ...
